List<String> getLyrics2() {
  return [
    'Hope stopped the heart',
    'Lost beaten lie',
    'Cold walk the earth',
    'Love faded white',
    'Gave up the war',
    'I\'ve realized',
    'All will become',
    'All will arise',
    'Stay with me',
    'I hear them call the tide',
    'Take me in',
    'I see the last divide',
    'Hopelessy',
    'I leave this all behind',
    'And I am paralyzed',
    'When the broken fall alive',
    'Let the light take me too',
    'When the waters turn to fire',
    'Heaven, please let me through',
    'Far away, far away',
    'Sorrow has left me here',
    'Far away, far away',
    'Let the light take me in',
    'Fight back the flood',
    'One breath of life',
    'God, take the earth',
    'Forever blind',
    'And now the sun will fade',
    'And all we are is all we made',
    'Stay with me',
    'I hear them call the tide',
    'Take me in',
    'I see the last divide',
    'Hopelessy',
    'I leave this all behind',
    'And I am paralyzed',
    'When the broken fall alive',
    'Let the light take me too',
    'When the waters…'
  ];
}

List<String> getLyrics() {
  return [
    'Eres como una mariposa',
    'Vuelas y te posas,'
    'vas de boca en boca',
    'Fácil y ligera de quien te provoca',
    'Yo soy ratón de tu ratonera',
    'Trampa que no mata pero no libera',
    'Vivo muriendo prisionero',
    'Mariposa traicionera',
    'Todo se lo lleva el viento',
    'Mariposa, no regreso',
    'Ay, mariposa de amor',
    'Mi mariposa de amor',
    'Ya no regreso contigo',
    'Ay, mariposa de amor',
    'Mi mariposa de amor',
    'Nunca jamás junto a ti',
    'Vuela amor',
    'Vuela dolor',
    'Y no regreses a un lado',
    'Ya vete de flor en flor',
    'Seduciendo',
    'A los pistilos',
    'Y vuela cerca del sol',
    'Pa que sientas lo que es dolor',
    'Ay, mujer cómo haces daño',
    'Pasan los minutos cual si fueran años',
    'Mira, estos celos, me están matando',
    'Ay, mujer qué fácil eres',
    'Abres tus alitas, muslos de colores',
    'Donde se posan tus amores',
    'Mariposa traicionera',
    'Todo se lo lleva el viento',
    'Mariposa, no regreso',
    'Ay, mariposa de amor',
    'Mi mariposa de amor',
    'Ya no regreso contigo',
    'Ay, mariposa de amor',
    'Mi mariposa de amor',
    'Nunca jamás junto a ti',
    'Vuela amor',
    'Vuela dolor',
    'Que tengas suerte en tu vida',
    'Ay, ay, ay, ay, ay dolor',
    'Yo te lloré todo un río',
    'Ay, ay, ay, ay, ay, amor',
    'Tú te me vas a volar',
  ];
}
